/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.48
 * Generated at: 2022-09-11 12:25:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/Серёга/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153374282000L));
    _jspx_dependants.put("file:/C:/Users/Серёга/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1653232043533L));
    _jspx_dependants.put("/WEB-INF/tag/language.tld", Long.valueOf(1662408800805L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Welcome page</title>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("    </head>\n");
      out.write("    <h1>\n");
      out.write("        ");
      if (_jspx_meth_lang_005fprint_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("     </h1>\n");
      out.write("    <body>\n");
      out.write("        <form action=\"/app/periodicals/login\" method=\"POST\">\n");
      out.write("            <label for=\"name\">");
      if (_jspx_meth_lang_005fprint_005f1(_jspx_page_context))
        return;
      out.write(":</label><br>\n");
      out.write("            <input type=\"text\" name=\"login\" pattern=\".{3,}\" title='");
      if (_jspx_meth_lang_005fprint_005f2(_jspx_page_context))
        return;
      out.write("' required ><br><br>\n");
      out.write("            <label for=\"pass\">");
      if (_jspx_meth_lang_005fprint_005f3(_jspx_page_context))
        return;
      out.write(":</label><br>\n");
      out.write("            <input type=\"password\" name=\"password\" pattern=\"(?=.*\\d)(?=.*[a-zа-яії])(?=.*[A-ZА-ЯІЇ]).{8,}\" title='");
      if (_jspx_meth_lang_005fprint_005f4(_jspx_page_context))
        return;
      out.write("' required><br><br>\n");
      out.write("            <input type = \"submit\" style=\"width: 8%\" value='");
      if (_jspx_meth_lang_005fprint_005f5(_jspx_page_context))
        return;
      out.write("'>\n");
      out.write("            <br><br>\n");
      out.write("            <input type = \"submit\" style=\"width: 8%\" formaction=\"/app/periodicals/reader/create\" value='");
      if (_jspx_meth_lang_005fprint_005f6(_jspx_page_context))
        return;
      out.write("'>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <br><br>\n");
      out.write("        <h3>\n");
      out.write("            ");
      if (_jspx_meth_lang_005fprint_005f7(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        </h3>\n");
      out.write("        <form accept-charset=\"UTF-8\" method=\"GET\" action=\"/app/periodicals/periodical/watch\">\n");
      out.write("            <input type=\"hidden\" name=\"page\" value=\"1\">\n");
      out.write("            <input type = \"submit\" style=\"width: 10%\" value='");
      if (_jspx_meth_lang_005fprint_005f8(_jspx_page_context))
        return;
      out.write("'>\n");
      out.write("        </form><br><br>\n");
      out.write("\n");
      out.write("        <form action = \"/app/periodicals/changeLocale\" method = \"POST\">\n");
      out.write("            <input type = \"hidden\" name = \"view\" value = \"/index.jsp\"/>\n");
      out.write("                <select name = \"selectedLocale\">\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                </select>\n");
      out.write("            <input type = \"submit\" value = 'Update'>\n");
      out.write("        </form>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_lang_005fprint_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f0 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f0_reused = false;
    try {
      _jspx_th_lang_005fprint_005f0.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f0.setParent(null);
      // /index.jsp(10,8) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f0.setMessage("index.jsp.welcome_to_app");
      int _jspx_eval_lang_005fprint_005f0 = _jspx_th_lang_005fprint_005f0.doStartTag();
      if (_jspx_th_lang_005fprint_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f0);
      _jspx_th_lang_005fprint_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f0, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f1 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f1_reused = false;
    try {
      _jspx_th_lang_005fprint_005f1.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f1.setParent(null);
      // /index.jsp(14,30) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f1.setMessage("index.jsp.label.login");
      int _jspx_eval_lang_005fprint_005f1 = _jspx_th_lang_005fprint_005f1.doStartTag();
      if (_jspx_th_lang_005fprint_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f1);
      _jspx_th_lang_005fprint_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f1, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f2 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f2_reused = false;
    try {
      _jspx_th_lang_005fprint_005f2.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f2.setParent(null);
      // /index.jsp(15,67) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f2.setMessage("index.jsp.input.login_validation");
      int _jspx_eval_lang_005fprint_005f2 = _jspx_th_lang_005fprint_005f2.doStartTag();
      if (_jspx_th_lang_005fprint_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f2);
      _jspx_th_lang_005fprint_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f2, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f3 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f3_reused = false;
    try {
      _jspx_th_lang_005fprint_005f3.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f3.setParent(null);
      // /index.jsp(16,30) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f3.setMessage("index.jsp.label.password");
      int _jspx_eval_lang_005fprint_005f3 = _jspx_th_lang_005fprint_005f3.doStartTag();
      if (_jspx_th_lang_005fprint_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f3);
      _jspx_th_lang_005fprint_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f3, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f4 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f4_reused = false;
    try {
      _jspx_th_lang_005fprint_005f4.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f4.setParent(null);
      // /index.jsp(17,114) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f4.setMessage("index.jsp.input.password_validation");
      int _jspx_eval_lang_005fprint_005f4 = _jspx_th_lang_005fprint_005f4.doStartTag();
      if (_jspx_th_lang_005fprint_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f4);
      _jspx_th_lang_005fprint_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f4, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f5 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f5_reused = false;
    try {
      _jspx_th_lang_005fprint_005f5.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f5.setParent(null);
      // /index.jsp(18,60) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f5.setMessage("index.jsp.button.sign_in");
      int _jspx_eval_lang_005fprint_005f5 = _jspx_th_lang_005fprint_005f5.doStartTag();
      if (_jspx_th_lang_005fprint_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f5);
      _jspx_th_lang_005fprint_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f5, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f6 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f6_reused = false;
    try {
      _jspx_th_lang_005fprint_005f6.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f6.setParent(null);
      // /index.jsp(20,104) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f6.setMessage("index.jsp.button.sign_up");
      int _jspx_eval_lang_005fprint_005f6 = _jspx_th_lang_005fprint_005f6.doStartTag();
      if (_jspx_th_lang_005fprint_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f6);
      _jspx_th_lang_005fprint_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f6, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f7 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f7_reused = false;
    try {
      _jspx_th_lang_005fprint_005f7.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f7.setParent(null);
      // /index.jsp(25,12) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f7.setMessage("index.jsp.if_u_are_not_registered");
      int _jspx_eval_lang_005fprint_005f7 = _jspx_th_lang_005fprint_005f7.doStartTag();
      if (_jspx_th_lang_005fprint_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f7);
      _jspx_th_lang_005fprint_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f7, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f8 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f8_reused = false;
    try {
      _jspx_th_lang_005fprint_005f8.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f8.setParent(null);
      // /index.jsp(29,61) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f8.setMessage("index.jsp.button.watch_periodicals");
      int _jspx_eval_lang_005fprint_005f8 = _jspx_th_lang_005fprint_005f8.doStartTag();
      if (_jspx_th_lang_005fprint_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f8);
      _jspx_th_lang_005fprint_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f8, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /index.jsp(35,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("locale");
      // /index.jsp(35,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/index.jsp(35,20) '${sessionScope.locales}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.locales}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                        <option value = \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locale}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("                            ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locale}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\n");
            out.write("                        </option>\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
