/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.48
 * Generated at: 2022-09-14 15:47:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.periodical;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class watchPeriodical_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/Серёга/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153374282000L));
    _jspx_dependants.put("file:/C:/Users/Серёга/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1653232043533L));
    _jspx_dependants.put("/WEB-INF/tag/language.tld", Long.valueOf(1662408800805L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>Reader page</title>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        <form action = \"/app/periodicals/periodical/search\" method = \"GET\">\r\n");
      out.write("            <label for=\"topic\">");
      if (_jspx_meth_lang_005fprint_005f0(_jspx_page_context))
        return;
      out.write(":</label>\r\n");
      out.write("            <select name=\"topic\">\r\n");
      out.write("                <option value=\"\"><no topic/></option>\r\n");
      out.write("                <option value=\"business\">");
      if (_jspx_meth_lang_005fprint_005f1(_jspx_page_context))
        return;
      out.write("</option>\r\n");
      out.write("                <option value=\"sport\" >");
      if (_jspx_meth_lang_005fprint_005f2(_jspx_page_context))
        return;
      out.write("</option>\r\n");
      out.write("                <option value=\"technology\">");
      if (_jspx_meth_lang_005fprint_005f3(_jspx_page_context))
        return;
      out.write("</option>\r\n");
      out.write("            </select>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"name\">");
      if (_jspx_meth_lang_005fprint_005f4(_jspx_page_context))
        return;
      out.write(":</label>\r\n");
      out.write("            <input type=\"text\" name=\"name\"  />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <input type = \"hidden\" name=\"page\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("            <button type =\"submit\">");
      if (_jspx_meth_lang_005fprint_005f5(_jspx_page_context))
        return;
      out.write("</button>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <form action = \"/app/periodicals/periodical/sortByCost\" method = \"GET\">\r\n");
      out.write("            <label for=\"name\">");
      if (_jspx_meth_lang_005fprint_005f6(_jspx_page_context))
        return;
      out.write(":</label><br>\r\n");
      out.write("            <input type = \"hidden\" name=\"topic\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("            <input type = \"hidden\" name=\"name\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("            <input type = \"hidden\" name=\"page\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("            <input type = \"submit\" value ='");
      if (_jspx_meth_lang_005fprint_005f7(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("            <input type = \"submit\" formaction=\"/app/periodicals/periodical/reversedSortByCost\" value='");
      if (_jspx_meth_lang_005fprint_005f8(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <form action =\"/app/periodicals/periodical/sortByName\" method = \"GET\">\r\n");
      out.write("            <label for=\"name\">");
      if (_jspx_meth_lang_005fprint_005f9(_jspx_page_context))
        return;
      out.write(":</label><br>\r\n");
      out.write("            <input type = \"hidden\" name=\"topic\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("            <input type = \"hidden\" name=\"name\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("            <input type = \"hidden\" name=\"page\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("            <input type = \"submit\" value ='");
      if (_jspx_meth_lang_005fprint_005f10(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("            <input type = \"submit\" formaction=\"/app/periodicals/periodical/reversedSortByName\" value='");
      if (_jspx_meth_lang_005fprint_005f11(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <form accept-charset=\"UTF-8\" method=\"GET\" action=\"/app/periodicals/periodical/watch\">\r\n");
      out.write("            <input type=\"hidden\" name=\"page\" value=\"1\">\r\n");
      out.write("            <label for=\"name\">");
      if (_jspx_meth_lang_005fprint_005f12(_jspx_page_context))
        return;
      out.write(":</label>\r\n");
      out.write("            <input type = \"submit\"  value='");
      if (_jspx_meth_lang_005fprint_005f13(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("            <br><br>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <button onclick=\"location.href='/app'\">");
      if (_jspx_meth_lang_005fprint_005f14(_jspx_page_context))
        return;
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("        <table id=\"listOfPeriodicals\">\r\n");
      out.write("        <caption>");
      if (_jspx_meth_lang_005fprint_005f15(_jspx_page_context))
        return;
      out.write("</caption>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>");
      if (_jspx_meth_lang_005fprint_005f16(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("                <th>");
      if (_jspx_meth_lang_005fprint_005f17(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("                <th>");
      if (_jspx_meth_lang_005fprint_005f18(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("                <th>");
      if (_jspx_meth_lang_005fprint_005f19(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </table>\r\n");
      out.write("\r\n");
      out.write("        <table align = \"center\">\r\n");
      out.write("            <th>");
      if (_jspx_meth_lang_005fprint_005f20(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("            <td align = \"center\">\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </td>\r\n");
      out.write("        </table>\r\n");
      out.write("\r\n");
      out.write("        <style>\r\n");
      out.write("            caption {\r\n");
      out.write("                font-family: annabelle;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("                font-size: 1.5em;\r\n");
      out.write("                padding: 10px;\r\n");
      out.write("                border: 1px solid #A9E2CC;\r\n");
      out.write("            }\r\n");
      out.write("            th {\r\n");
      out.write("                padding: 10px;\r\n");
      out.write("                border: 1px solid #A9E2CC;\r\n");
      out.write("            }\r\n");
      out.write("            td {\r\n");
      out.write("                font-size: 1.0em;\r\n");
      out.write("                padding: 5px 7px;\r\n");
      out.write("                border: 1px solid #A9E2CC;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_lang_005fprint_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f0 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f0_reused = false;
    try {
      _jspx_th_lang_005fprint_005f0.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f0.setParent(null);
      // /periodical/watchPeriodical.jsp(12,31) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f0.setMessage("periodical.periodicalForSubscribing.jsp.label.find_periodical_by_topic");
      int _jspx_eval_lang_005fprint_005f0 = _jspx_th_lang_005fprint_005f0.doStartTag();
      if (_jspx_th_lang_005fprint_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f0);
      _jspx_th_lang_005fprint_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f0, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f1 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f1_reused = false;
    try {
      _jspx_th_lang_005fprint_005f1.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f1.setParent(null);
      // /periodical/watchPeriodical.jsp(15,41) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f1.setMessage("periodical.periodicalForSubscribing.jsp.option.business");
      int _jspx_eval_lang_005fprint_005f1 = _jspx_th_lang_005fprint_005f1.doStartTag();
      if (_jspx_th_lang_005fprint_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f1);
      _jspx_th_lang_005fprint_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f1, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f2 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f2_reused = false;
    try {
      _jspx_th_lang_005fprint_005f2.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f2.setParent(null);
      // /periodical/watchPeriodical.jsp(16,39) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f2.setMessage("periodical.periodicalForSubscribing.jsp.option.sport");
      int _jspx_eval_lang_005fprint_005f2 = _jspx_th_lang_005fprint_005f2.doStartTag();
      if (_jspx_th_lang_005fprint_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f2);
      _jspx_th_lang_005fprint_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f2, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f3 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f3_reused = false;
    try {
      _jspx_th_lang_005fprint_005f3.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f3.setParent(null);
      // /periodical/watchPeriodical.jsp(17,43) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f3.setMessage("periodical.periodicalForSubscribing.jsp.option.technology");
      int _jspx_eval_lang_005fprint_005f3 = _jspx_th_lang_005fprint_005f3.doStartTag();
      if (_jspx_th_lang_005fprint_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f3);
      _jspx_th_lang_005fprint_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f3, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f4 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f4_reused = false;
    try {
      _jspx_th_lang_005fprint_005f4.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f4.setParent(null);
      // /periodical/watchPeriodical.jsp(20,30) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f4.setMessage("periodical.periodicalForSubscribing.jsp.label.find_periodical_by_name");
      int _jspx_eval_lang_005fprint_005f4 = _jspx_th_lang_005fprint_005f4.doStartTag();
      if (_jspx_th_lang_005fprint_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f4);
      _jspx_th_lang_005fprint_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f4, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f5 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f5_reused = false;
    try {
      _jspx_th_lang_005fprint_005f5.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f5.setParent(null);
      // /periodical/watchPeriodical.jsp(25,35) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f5.setMessage("periodical.periodicalForSubscribing.jsp.button.search");
      int _jspx_eval_lang_005fprint_005f5 = _jspx_th_lang_005fprint_005f5.doStartTag();
      if (_jspx_th_lang_005fprint_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f5);
      _jspx_th_lang_005fprint_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f5, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f6 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f6_reused = false;
    try {
      _jspx_th_lang_005fprint_005f6.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f6.setParent(null);
      // /periodical/watchPeriodical.jsp(31,30) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f6.setMessage("periodical.watchPeriodical.jsp.label.sort_periodicals_by_cost");
      int _jspx_eval_lang_005fprint_005f6 = _jspx_th_lang_005fprint_005f6.doStartTag();
      if (_jspx_th_lang_005fprint_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f6);
      _jspx_th_lang_005fprint_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f6, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f7 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f7_reused = false;
    try {
      _jspx_th_lang_005fprint_005f7.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f7.setParent(null);
      // /periodical/watchPeriodical.jsp(35,43) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f7.setMessage("periodical.watchPeriodical.jsp.button.sort");
      int _jspx_eval_lang_005fprint_005f7 = _jspx_th_lang_005fprint_005f7.doStartTag();
      if (_jspx_th_lang_005fprint_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f7);
      _jspx_th_lang_005fprint_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f7, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f8 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f8_reused = false;
    try {
      _jspx_th_lang_005fprint_005f8.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f8.setParent(null);
      // /periodical/watchPeriodical.jsp(36,102) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f8.setMessage("periodical.watchPeriodical.jsp.button.reversed_sort");
      int _jspx_eval_lang_005fprint_005f8 = _jspx_th_lang_005fprint_005f8.doStartTag();
      if (_jspx_th_lang_005fprint_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f8);
      _jspx_th_lang_005fprint_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f8, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f9 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f9_reused = false;
    try {
      _jspx_th_lang_005fprint_005f9.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f9.setParent(null);
      // /periodical/watchPeriodical.jsp(40,30) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f9.setMessage("periodical.watchPeriodical.jsp.label.sort_periodicals_by_name");
      int _jspx_eval_lang_005fprint_005f9 = _jspx_th_lang_005fprint_005f9.doStartTag();
      if (_jspx_th_lang_005fprint_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f9);
      _jspx_th_lang_005fprint_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f9, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f10 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f10_reused = false;
    try {
      _jspx_th_lang_005fprint_005f10.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f10.setParent(null);
      // /periodical/watchPeriodical.jsp(44,43) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f10.setMessage("periodical.watchPeriodical.jsp.button.sort");
      int _jspx_eval_lang_005fprint_005f10 = _jspx_th_lang_005fprint_005f10.doStartTag();
      if (_jspx_th_lang_005fprint_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f10);
      _jspx_th_lang_005fprint_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f10, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f11 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f11_reused = false;
    try {
      _jspx_th_lang_005fprint_005f11.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f11.setParent(null);
      // /periodical/watchPeriodical.jsp(45,102) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f11.setMessage("periodical.watchPeriodical.jsp.button.reversed_sort");
      int _jspx_eval_lang_005fprint_005f11 = _jspx_th_lang_005fprint_005f11.doStartTag();
      if (_jspx_th_lang_005fprint_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f11);
      _jspx_th_lang_005fprint_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f11, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f12 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f12_reused = false;
    try {
      _jspx_th_lang_005fprint_005f12.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f12.setParent(null);
      // /periodical/watchPeriodical.jsp(50,30) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f12.setMessage("periodical.watchPeriodical.jsp.label.click_to_see_all_periodicals");
      int _jspx_eval_lang_005fprint_005f12 = _jspx_th_lang_005fprint_005f12.doStartTag();
      if (_jspx_th_lang_005fprint_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f12);
      _jspx_th_lang_005fprint_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f12, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f12_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f13 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f13_reused = false;
    try {
      _jspx_th_lang_005fprint_005f13.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f13.setParent(null);
      // /periodical/watchPeriodical.jsp(51,43) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f13.setMessage("periodical.watchPeriodical.jsp.button.all_periodicals");
      int _jspx_eval_lang_005fprint_005f13 = _jspx_th_lang_005fprint_005f13.doStartTag();
      if (_jspx_th_lang_005fprint_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f13);
      _jspx_th_lang_005fprint_005f13_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f13, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f13_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f14 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f14_reused = false;
    try {
      _jspx_th_lang_005fprint_005f14.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f14.setParent(null);
      // /periodical/watchPeriodical.jsp(55,47) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f14.setMessage("periodical.watchPeriodical.jsp.button.back_to_registration");
      int _jspx_eval_lang_005fprint_005f14 = _jspx_th_lang_005fprint_005f14.doStartTag();
      if (_jspx_th_lang_005fprint_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f14);
      _jspx_th_lang_005fprint_005f14_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f14, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f14_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f15 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f15_reused = false;
    try {
      _jspx_th_lang_005fprint_005f15.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f15.setParent(null);
      // /periodical/watchPeriodical.jsp(58,17) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f15.setMessage("periodical.watchPeriodical.jsp.table.caption.periodicals");
      int _jspx_eval_lang_005fprint_005f15 = _jspx_th_lang_005fprint_005f15.doStartTag();
      if (_jspx_th_lang_005fprint_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f15);
      _jspx_th_lang_005fprint_005f15_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f15, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f15_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f16(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f16 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f16_reused = false;
    try {
      _jspx_th_lang_005fprint_005f16.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f16.setParent(null);
      // /periodical/watchPeriodical.jsp(60,20) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f16.setMessage("periodical.periodicalForSubscribing.jsp.table.name");
      int _jspx_eval_lang_005fprint_005f16 = _jspx_th_lang_005fprint_005f16.doStartTag();
      if (_jspx_th_lang_005fprint_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f16);
      _jspx_th_lang_005fprint_005f16_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f16, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f16_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f17(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f17 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f17_reused = false;
    try {
      _jspx_th_lang_005fprint_005f17.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f17.setParent(null);
      // /periodical/watchPeriodical.jsp(61,20) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f17.setMessage("periodical.periodicalForSubscribing.jsp.table.topic");
      int _jspx_eval_lang_005fprint_005f17 = _jspx_th_lang_005fprint_005f17.doStartTag();
      if (_jspx_th_lang_005fprint_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f17);
      _jspx_th_lang_005fprint_005f17_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f17, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f17_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f18(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f18 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f18_reused = false;
    try {
      _jspx_th_lang_005fprint_005f18.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f18.setParent(null);
      // /periodical/watchPeriodical.jsp(62,20) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f18.setMessage("periodical.periodicalForSubscribing.jsp.table.cost");
      int _jspx_eval_lang_005fprint_005f18 = _jspx_th_lang_005fprint_005f18.doStartTag();
      if (_jspx_th_lang_005fprint_005f18.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f18);
      _jspx_th_lang_005fprint_005f18_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f18, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f18_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f19(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f19 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f19_reused = false;
    try {
      _jspx_th_lang_005fprint_005f19.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f19.setParent(null);
      // /periodical/watchPeriodical.jsp(63,20) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f19.setMessage("periodical.periodicalForSubscribing.jsp.table.description");
      int _jspx_eval_lang_005fprint_005f19 = _jspx_th_lang_005fprint_005f19.doStartTag();
      if (_jspx_th_lang_005fprint_005f19.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f19);
      _jspx_th_lang_005fprint_005f19_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f19, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f19_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /periodical/watchPeriodical.jsp(65,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/periodical/watchPeriodical.jsp(65,8) '${periodicals}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${periodicals}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /periodical/watchPeriodical.jsp(65,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("periodical");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("            <tr>\r\n");
            out.write("                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${periodical.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${periodical.topic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${periodical.cost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${periodical.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("            </tr>\r\n");
            out.write("        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f20(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lang:print
    org.periodicals.epam.spring.project.infra.web.LanguageTag _jspx_th_lang_005fprint_005f20 = (org.periodicals.epam.spring.project.infra.web.LanguageTag) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(org.periodicals.epam.spring.project.infra.web.LanguageTag.class);
    boolean _jspx_th_lang_005fprint_005f20_reused = false;
    try {
      _jspx_th_lang_005fprint_005f20.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f20.setParent(null);
      // /periodical/watchPeriodical.jsp(76,16) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f20.setMessage("periodical.watchPeriodical.jsp.pages");
      int _jspx_eval_lang_005fprint_005f20 = _jspx_th_lang_005fprint_005f20.doStartTag();
      if (_jspx_th_lang_005fprint_005f20.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f20);
      _jspx_th_lang_005fprint_005f20_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f20, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f20_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /periodical/watchPeriodical.jsp(78,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${countOfPages != 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /periodical/watchPeriodical.jsp(79,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("i");
      // /periodical/watchPeriodical.jsp(79,20) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(1);
      // /periodical/watchPeriodical.jsp(79,20) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${countOfPages}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                        ");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("                        ");
            if (_jspx_meth_c_005fif_005f8(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /periodical/watchPeriodical.jsp(80,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i != page}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("                            ");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("                            ");
          if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fif_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("                            ");
          if (_jspx_meth_c_005fif_005f5(_jspx_th_c_005fif_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("                            ");
          if (_jspx_meth_c_005fif_005f6(_jspx_th_c_005fif_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("                            ");
          if (_jspx_meth_c_005fif_005f7(_jspx_th_c_005fif_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /periodical/watchPeriodical.jsp(81,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path == '/app/periodicals/periodical/watch'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <a href=\"/app/periodicals/periodical/watch?page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">  < ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" >  </a>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /periodical/watchPeriodical.jsp(84,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path == '/app/periodicals/periodical/search'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <a href=\"/app/periodicals/periodical/search?topic=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&name=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">  < ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" >  </a>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /periodical/watchPeriodical.jsp(87,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path == '/app/periodicals/periodical/sortByCost'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <a href=\"/app/periodicals/periodical/sortByCost?topic=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&name=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">  < ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" >  </a>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /periodical/watchPeriodical.jsp(90,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path == '/app/periodicals/periodical/reversedSortByCost'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <a href=\"/app/periodicals/periodical/reversedSortByCost?topic=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&name=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">  < ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" >  </a>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /periodical/watchPeriodical.jsp(93,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path == '/app/periodicals/periodical/sortByName'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <a href=\"/app/periodicals/periodical/sortByName?topic=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&name=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">  < ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" >  </a>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /periodical/watchPeriodical.jsp(96,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path == '/app/periodicals/periodical/reversedSortByName'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <a href=\"/app/periodicals/periodical/reversedSortByName?topic=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&name=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">  < ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" >  </a>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f8_reused = false;
    try {
      _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /periodical/watchPeriodical.jsp(100,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i == page}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
      if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            <a>  < ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" >  </a>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
      _jspx_th_c_005fif_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f8_reused);
    }
    return false;
  }
}
